[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "zero-tensorflow"
version = "2.20.0"
description = "Zero-dependency pure Python implementation of the TensorFlow API surface."
authors = [{ name = "Samuel Marks" }]
requires-python = ">=3.9"
dynamic = ["dependencies"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.metadata]
allow-direct-references = true

dependencies = ["ml-switcheroo-compiler"]

[tool.ruff]
ignore = ['E402']

[tool.mypy]
ignore_missing_imports = true
